import { Rider } from "@/types/riders";

export const MOCK_RIDERS: Rider[] = [
  {
    id: "RDR-8291A",
    name: "Tinashe Makoni",
    phone: "+263 77 123 4567",
    vehicleType: "Motorbike",
    licensePlate: "ABT 1245",
    status: "Available",
    distanceKm: 0.3,
    rating: 4.8,
    totalDeliveries: 1245,
    lastActive: "Just now",
    avatarUrl: "https://i.pravatar.cc/150?u=tinashe",
  },
  {
    id: "RDR-7102B",
    name: "Chipo Moyo",
    phone: "+263 78 987 6543",
    vehicleType: "Motorbike",
    licensePlate: "ACX 8991",
    status: "Dispatched",
    distanceKm: 2.1,
    rating: 4.9,
    totalDeliveries: 892,
    lastActive: "10 mins ago",
    avatarUrl: "https://i.pravatar.cc/150?u=chipo",
  },
  {
    id: "RDR-4409C",
    name: "Tafadzwa Ndlovu",
    phone: "+263 71 555 4444",
    vehicleType: "Van",
    licensePlate: "AEC 3310",
    status: "Offline",
    distanceKm: 5.0,
    rating: 4.5,
    totalDeliveries: 430,
    lastActive: "2 hours ago",
    avatarUrl: "https://i.pravatar.cc/150?u=tafadzwa",
  },
  {
    id: "RDR-1198D",
    name: "Kudzai Chibanda",
    phone: "+263 73 222 1111",
    vehicleType: "Motorbike",
    licensePlate: "ABD 7762",
    status: "Banned",
    distanceKm: 12.4,
    rating: 3.2,
    totalDeliveries: 112,
    lastActive: "3 days ago",
    avatarUrl: "https://i.pravatar.cc/150?u=kudzai",
  },
  {
    id: "RDR-6621E",
    name: "Blessing Mutero",
    phone: "+263 77 888 9999",
    vehicleType: "Bicycle",
    licensePlate: "N/A",
    status: "Available",
    distanceKm: 0.1,
    rating: 4.7,
    totalDeliveries: 504,
    lastActive: "Just now",
    avatarUrl: "https://i.pravatar.cc/150?u=blessing",
  },
  {
    id: "RDR-9012F",
    name: "Simbarashe Gumbo",
    phone: "+263 78 333 4444",
    vehicleType: "Motorbike",
    licensePlate: "ACR 2219",
    status: "Dispatched",
    distanceKm: 1.5,
    rating: 4.6,
    totalDeliveries: 760,
    lastActive: "5 mins ago",
    avatarUrl: "https://i.pravatar.cc/150?u=simbarashe",
  }
];
