import { WasteLogEntry } from "@/types/waste";

export const MOCK_WASTE_LOGS: WasteLogEntry[] = [
  {
    id: "WL-2026-001",
    productId: "PRD-221",
    productName: "Fresh Milk 2L",
    sku: "FM-2L-001",
    category: "Dairy",
    quantity: 5,
    unitCost: 2.50,
    totalLoss: 12.50,
    reason: "Expired",
    loggedBy: "John Doe (Manager)",
    timestamp: "2026-02-25T08:30:00Z",
    notes: "Found during morning stock check. Expiry date was yesterday.",
  },
  {
    id: "WL-2026-002",
    productId: "PRD-593",
    productName: "Canned Tomatoes 400g",
    sku: "CT-400-92",
    category: "Pantry",
    quantity: 2,
    unitCost: 1.20,
    totalLoss: 2.40,
    reason: "Damaged",
    loggedBy: "Jane Smith (Supervisor)",
    timestamp: "2026-02-24T14:15:00Z",
    notes: "Dented cans found upon delivery from supplier.",
  },
  {
    id: "WL-2026-003",
    productId: "PRD-102",
    productName: "Olive Oil Extra Virgin 500ml",
    sku: "OO-EV-500",
    category: "Oils",
    quantity: 1,
    unitCost: 9.50,
    totalLoss: 9.50,
    reason: "Leaked",
    loggedBy: "John Doe (Manager)",
    timestamp: "2026-02-23T16:45:00Z",
    notes: "Dropped by customer in aisle 3.",
  },
  {
    id: "WL-2026-004",
    productId: "PRD-884",
    productName: "Bananas (Loose)",
    sku: "BN-LSE-00",
    category: "Produce",
    quantity: 4.5,
    unitCost: 1.10,
    totalLoss: 4.95,
    reason: "Spoilage",
    loggedBy: "Mike Rogers (Stock Clerk)",
    timestamp: "2026-02-22T09:10:00Z",
    notes: "Overripe and spotted, removed from display.",
  },
  {
    id: "WL-2026-005",
    productId: "PRD-324",
    productName: "Premium Dark Chocolate",
    sku: "CHOC-DK-1",
    category: "Sweets",
    quantity: 3,
    unitCost: 4.00,
    totalLoss: 12.00,
    reason: "Lost",
    loggedBy: "John Doe (Manager)",
    timestamp: "2026-02-21T18:00:00Z",
    notes: "Stock take discrepancy. Items missing from shelf.",
  },
  {
    id: "WL-2026-006",
    productId: "PRD-119",
    productName: "Greek Yogurt Vanilla",
    sku: "YG-GRK-V",
    category: "Dairy",
    quantity: 8,
    unitCost: 3.50,
    totalLoss: 28.00,
    reason: "Expired",
    loggedBy: "Sarah Clark (Supervisor)",
    timestamp: "2026-02-20T07:45:00Z",
    notes: "Cold chain failure during transit, temperature log flagged.",
  },
];
